#!/bin/sh

generatePassword() {
    if [ $1 ] ; then
        openssl rand -base64 $1
    else 
        openssl rand -base64 8
    fi
}

decodeBase64() {
    echo $1 | base64 --decode ; echo
}        

encodeBase64() {
    echo $1 | base64  ; echo
}      

showUsingPort() {
    netstat -nlp 
}

extract () {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1     ;;
            *.tar.gz)    tar xzf $1     ;;
            *.bz2)       bunzip2 $1     ;;
            *.rar)       unrar e $1     ;;
            *.gz)        gunzip $1     ;;
            *.tar)       tar xf $1      ;;
            *.tbz2)      tar xjf $1     ;;
            *.tgz)       tar xzf $1     ;;
            *.zip)       unzip $1       ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1        ;;
            *)     echo "'$1' cannot be extracted via extract()" ;
        esac
    else
        echo "$1 is not a valid file"
    fi
}

make_clean_install() {
	sudo make uninstall
	sudo make clean install
}

ip4() {
    curl -4 ifconfig.co
}

ip6() {
    curl -6 ifconfig.co
}

openPDF() {
    nohup zathura $(fzf)
}

getHttpStatusCode() {
    curl -s -o /dev/null -w "%{http_code}\n" $1
}

killAllDockerContainer() {
    docker rm -f $(docker ps -aq)
}


