#!/bin/sh

generatePassword() {
    if [ $1 ] ; then
        openssl rand -base64 $1
    else 
        openssl rand -base64 8
    fi
}

decodeBase64() {
    echo $1 | base64 --decode ; echo
}        

encodeBase64() {
    echo $1 | base64  ; echo
}      

showUsingPort() {
    netstat -nlp 
}

make_clean_install() {
	sudo make uninstall
	sudo make clean install
}

ip4() {
    curl -4 ifconfig.co
}

ip6() {
    curl -6 ifconfig.co
}

openPDF() {
    nohup zathura $(fzf)
}

getHttpStatusCode() {
    curl -s -o /dev/null -w "%{http_code}\n" $1
}

killAllDockerContainer() {
    docker rm -f $(docker ps -aq)
}

note() {
    cd ~/Notes/
    nvim .
}

startService() {
    sudo systemctl start $1
}

live_server() { 
    npx live-server $1
}
