#!/bin/sh
# Function to source files if they exist
function z_source() {
    [ -f "$HOME/.config/zsh/$1" ] && source "$HOME/.config/zsh/$1"
}

function z_plug() {
    local full_plugin_name="$1"
    local plugin_name=$(echo "$full_plugin_name" | cut -d "/" -f 2)
    ZAP_PLUGIN_DIR=$ZDOTDIR/plugins
    if [ ! -d "$ZAP_PLUGIN_DIR/$plugin_name" ]; then
      echo "Installing $plugin_name ..." && git clone "https://github.com/${full_plugin_name}.git" \
        "$ZAP_PLUGIN_DIR/$plugin_name" > /dev/null 2>&1 && echo " $plugin_name " || echo "Failed to install : $plugin_name"
    fi
    source "$ZAP_PLUGIN_DIR/$plugin_name/$plugin_name.plugin.zsh" || \
    source "$ZAP_PLUGIN_DIR/$plugin_name/$plugin_name.zsh" || \
    source "$ZAP_PLUGIN_DIR/$plugin_name/$plugin_name.zsh-theme"
}

function z_cmp() {
    ZAP_PLUGIN_DIR=$ZDOTDIR/plugins
    local full_plugin_name="$1"
    local initialize_completion="$2"
    local plugin_name=$(echo "$full_plugin_name" | cut -d "/" -f 2)
    if [ ! -d "$ZAP_PLUGIN_DIR/$plugin_name" ]; then
        git clone "https://github.com/${full_plugin_name}.git" "$ZAP_PLUGIN_DIR/$plugin_name" \
          > /dev/null 2>&1 && echo " $plugin_name " || echo "Failed to install : $plugin_name"
        fpath+=$(ls $ZAP_PLUGIN_DIR/$plugin_name/_*)
        [ -f $ZAP_DIR/.zccompdump ] && $ZAP_DIR/.zccompdump
    fi
    local completion_file_path=$(ls $ZAP_PLUGIN_DIR/$plugin_name/_*)
    if [[ $completion_file_path = "" ]]; then
        completion_file_path=$(ls $ZAP_PLUGIN_DIR/$plugin_name/src/_*)
    fi
    fpath+="$(dirname "${completion_file_path}")"
    z_source $ZAP_PLUGIN_DIR/$plugin_name/$plugin_name.plugin.zsh
    local completion_file="$(basename "${completion_file_path}")"
    [ "$initialize_completion" = true ] && compinit "${completion_file:1}"
}
